### ISSUE TITLE
Updating to Core 2023.8.0 fails

### ISSUE THREAD

**Issue by frankfrommelt** [Kannix2005/homeassistant-selve#19]
Hi,

I am running Selve NG 3.0.5-1 with Core 2023.7.3.

Updating Core to 2023.8.0 fails.

I found the following in the "supervisor.log" 
23-08-03 12:31:31 ERROR (MainThread) [supervisor.homeassistant.core] Home Assistant has crashed!
23-08-03 12:31:31 CRITICAL (MainThread) [supervisor.homeassistant.core] HomeAssistant update failed -> rollback!

The "rollback.log" says:
**_2023-08-03 12:31:22.010 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for selve:  we are unable to resolve (sub)dependency discovery_**
2023-08-03 12:31:22.065 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 226, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 214, in main
    exit_code = runner.run(runtime_conf)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 146, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 155, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 299, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 576, in _async_set_up_integrations
    for dep in itg.all_dependencies:
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 758, in all_dependencies
    raise RuntimeError("Dependencies not resolved!")
RuntimeError: Dependencies not resolved!

So, I suspect the Selve integration not being compatible with Core 2023.8.0

Regards
   Frank

**Comment by berndklug1107** [comment]
Hi !
I have the same problem with my selve integration (selve-RF-USB). Tried several options (e.g. supervised debian bookworm, raspi HA OS -> to ensure that all libs are 100% correct) but no chance. I'm also quite sure the 2023.8 ver does not match with selve, no matter which platform.
BR bernd

**Comment by frankfrommelt** [comment]
It seems the dependancy on the removed "legacy discovery integration" is preventing the selve integration to load.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IMMIhomeassistant** [comment]
unfortainly the same issue here

all fully updated on haos system
selve 3.0.5-1
trying update home assistant cor from 2023.7.3 to 2023.8.0 and 2023.8.1
also whisper and piper fails because of home assistant core isnt updated

**Comment by Kannix2005** [comment]
Fixed ;)

**Comment by berndklug1107** [comment]
... thank u! good man 👍

**Comment by rai-rob** [comment]
Thnx for the fast fix 👍

**Comment by IMMIhomeassistant** [comment]
Youre the best stefan

⁣BlueMail voor Android downloaden ​

Op 9 aug. 2023 21:44, om 21:44, rai-rob ***@***.***> schreef:

**Comment by frankfrommelt** [comment]
Thank you!
