### ISSUE TITLE
Problem since the last version

### ISSUE THREAD

**Issue by chekdo** [Kannix2005/homeassistant-selve#25]
**Describe the bug**
I can't start the component

**To Reproduce**
Since I install the last version of homeassistant, I can't load the component.

**Expected behavior**
I have this message in the logs.

**Screenshots**
`Enregistreur: homeassistant.config_entries
Source: config_entries.py:575
S'est produit pour la première fois: 20:49:21 (1 occurrences)
Dernier enregistrement: 20:49:21
Error setting up entry Selve Gateway for selve

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/selve/__init__.py", line 63, in async_setup_entry
    return await selvegat.async_setup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/selve/__init__.py", line 127, in async_setup
    await self.controller.setup(discover=True)
  File "/usr/local/lib/python3.12/site-packages/selve/__init__.py", line 182, in setup
    if await self.pingGateway(fromConfigFlow=fromConfigFlow):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selve/__init__.py", line 889, in pingGateway
    methodResponse = await self.executeCommandSyncWithResponse(cmd, fromConfigFlow=fromConfigFlow)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selve/__init__.py", line 548, in executeCommandSyncWithResponse
    resp = await self._executeCommandSyncWithResponse(command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selve/__init__.py", line 576, in _executeCommandSyncWithResponse
    response = self._serial.readline().strip()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

**Desktop (please complete the following information):**
 -  Core 2024.5.2
- Supervisor 2024.05.1
- Operating System 12.3
- Interface utilisateur 20240501.1
Thanks for helping.

**Comment by chekdo** [comment]
I change where the dongle is plug and the problem is solved.
