### ISSUE TITLE
updating Homeassistant core from 2024.6.3 to 2024.6.4 fails

### ISSUE THREAD

**Issue by frankfrommelt** [Kannix2005/homeassistant-selve#26]
Hi Stefan,

updating Homeassistant core from 2024.6.3 to  2024.6.4 fails and I get a rollback.

The below error is in my home-assistant-rollback.log 15 times:

2024-06-21 23:48:56.904 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'selve' at custom_components/selve/__init__.py, line 127: await self.controller.setup(discover=True) (offender: /usr/local/lib/python3.12/site-packages/serial/tools/list_ports_linux.py, line 84: with open(os.path.join(*args)) as f:), please create a bug report at https://github.com/Kannix2005/homeassistant-selve/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/selve/__init__.py", line 63, in async_setup_entry
    return await selvegat.async_setup()
  File "/config/custom_components/selve/__init__.py", line 127, in async_setup
    await self.controller.setup(discover=True)

I have 6 Selve Commeo devices that are working perfectly before the update and after the rollback (with the previous version 2024.6.3).

Please help

   Frank

**Comment by frankfrommelt** [comment]
Hi Stefan,
OK, no change of anything but now the update has completed without of any problems.
Cheers
   Frank
