### ISSUE TITLE
Update from 3.0.14 to version 3.0.19 is "problematic"

### ISSUE THREAD

**Issue by frankfrommelt** [Kannix2005/homeassistant-selve#30]
Hi Stefan,
after updating to 3.0.19 I got the error that the integration has an issue.
I could still operate my blinds.
I remember an error that the integration was referring to "set.led_staus" and if python was realy meaning "get.led_status" (or vice versa).
When re-loading the integration the whole core was stuck and I hat to kill the core docker container (docker kill ...) and re-start the container (ha core start).
Which brought me back to the "integration has an issue".
I now downgraded to 3.0.14 and am back to normal state.

I manually updated the python_selve_library to v21 as it never update automatically.
But that did not change the issue with 3.0.19.

I am still at core 2024.8.3.

**Comment by Kannix2005** [comment]
What exactly is the error here? Can you give me an extract of your log?

**Comment by frankfrommelt** [comment]
By the way,

 �

Set LED on and off actually and other actions work as expected.

 �

E.g.

 �



 �



 �

 �

 �

Von: ***@***.*** ***@***.***> 
Gesendet: Donnerstag, 5. September 2024 14:56
An: 'Kannix2005/homeassistant-selve' ***@***.***>; 'Kannix2005/homeassistant-selve' ***@***.***>
Cc: 'Author' ***@***.***>
Betreff: AW: [Kannix2005/homeassistant-selve] Update from 3.0.14 to version 3.0.19 is "problematic" (Issue #30)

 �

Hi Stefan,

 �

this is with 3.0.20, but it is the same behavior:

 �



 �

This is what I found in my log:

 �

2024-09-05 14:46:53.263 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'selve' calls async_forward_entry_setup for integration, selve with title: selve and entry_id: 9b86273195bc7f15865dd803df2d07c4, which is deprecated and will stop working in

2024-09-05 14:46:53.267 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'selve' calls async_forward_entry_setup for integration, selve with title: selve and entry_id: 9b86273195bc7f15865dd803df2d07c4, which is deprecated and will stop working in

2024-09-05 14:46:53.268 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry selve for selve

Traceback (most recent call last):

   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup

       result = await component.async_setup_entry(hass, self)

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   File "/config/custom_components/selve/__init__.py", line 64, in async_setup_entry

       await selvegat.async_setup()

   File "/config/custom_components/selve/__init__.py", line 185, in async_setup

       hass.services.async_register(DOMAIN, 'get_led', self.get_led, supports_response=SupportsResponse.OPTIONAL)

                                                                                                       ^^^^^^^^^^^^

AttributeError: 'SelveGateway' object has no attribute 'get_led'. Did you mean: 'set_led'?

2024-09-05 14:46:53.277 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration selve with title: selve and entry_id: 9b86273195bc7f15865dd803df2d07c4, during setup without awaiting async_forward_entry_setup, which can

Stack (most recent call last):

   File "<frozen runpy>", line 198, in _run_module_as_main

   File "<frozen runpy>", line 88, in _run_code

   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>

       sys.exit(main())

   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main

       exit_code = runner.run(runtime_conf)

   File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run

       return loop.run_until_complete(setup_and_run_hass(runtime_config))

   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete

       self.run_forever()

   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever

       self._run_once()

   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once

       handle._run()

   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run

       self._context.run(self._callback, *self._args)

   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup

       _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")

   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards

       report(

   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report

       _LOGGER.warning(msg, stack_info=True)

2024-09-05 14:46:53.282 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration selve with title: selve and entry_id: 9b86273195bc7f15865dd803df2d07c4, during setup without awaiting async_forward_entry_setup, which can

Stack (most recent call last):

   File "<frozen runpy>", line 198, in _run_module_as_main

   File "<frozen runpy>", line 88, in _run_code

   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>

       sys.exit(main())

   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main

       exit_code = runner.run(runtime_conf)

   File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run

       return loop.run_until_complete(setup_and_run_hass(runtime_config))

   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete

       self.run_forever()

   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever

       self._run_once()

   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once

       handle._run()

   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run

       self._context.run(self._callback, *self._args)

   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup

       _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")

   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards

       report(

   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report

       _LOGGER.warning(msg, stack_info=True)

 �

Take care

 �

 � � � � Frank

 �

Von: Stefan Altheimer ***@***.*** ***@***.***> > 
Gesendet: Donnerstag, 5. September 2024 13:01
An: Kannix2005/homeassistant-selve ***@***.*** ***@***.***> >
Cc: Frank Frommelt ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Betreff: Re: [Kannix2005/homeassistant-selve] Update from 3.0.14 to version 3.0.19 is "problematic" (Issue #30)

 �

What exactly is the error here? Can you give me an extract of your log?

**Comment by frankfrommelt** [comment]
Fixed with 3.0.21!!! :-)
Thank you Stefan!

**Comment by frankfrommelt** [comment]
Fixed with 3.0.21!!! :-)
Thank you Stefan!
